[LOG] [2025-01-05 20:30:28] IP 127.0.0.1 tried to access /api/v1/dev/logs and received status 200  - 2025-01-05 20:30:28,711
127.0.0.1 - - [05/Jan/2025 20:30:28] "DELETE /api/v1/dev/logs HTTP/1.1" 200 - - 2025-01-05 20:30:28,712
[LOG] [2025-01-05 20:30:28] IP 127.0.0.1 tried to access /api/v1/dev/logs and received status 200  - 2025-01-05 20:30:28,723
127.0.0.1 - - [05/Jan/2025 20:30:28] "GET /api/v1/dev/logs HTTP/1.1" 200 - - 2025-01-05 20:30:28,723
[LOG] [2025-01-05 20:30:29] IP 127.0.0.1 tried to access /dev/dashboard/logs and received status 200  - 2025-01-05 20:30:29,263
127.0.0.1 - - [05/Jan/2025 20:30:29] "GET /dev/dashboard/logs HTTP/1.1" 200 - - 2025-01-05 20:30:29,263
[LOG] [2025-01-05 20:30:29] IP 127.0.0.1 tried to access /api/v1/dev/logs and received status 200  - 2025-01-05 20:30:29,407
127.0.0.1 - - [05/Jan/2025 20:30:29] "GET /api/v1/dev/logs HTTP/1.1" 200 - - 2025-01-05 20:30:29,407
[LOG] [2025-01-05 20:30:29] IP 127.0.0.1 tried to access /dev/dashboard/token_request and received status 200  - 2025-01-05 20:30:29,865
127.0.0.1 - - [05/Jan/2025 20:30:29] "GET /dev/dashboard/token_request HTTP/1.1" 200 - - 2025-01-05 20:30:29,866
[LOG] [2025-01-05 20:30:30] IP 127.0.0.1 tried to access /api/v1/dev/pending_requests and received status 200  - 2025-01-05 20:30:30,026
127.0.0.1 - - [05/Jan/2025 20:30:30] "GET /api/v1/dev/pending_requests HTTP/1.1" 200 - - 2025-01-05 20:30:30,027
[LOG] [2025-01-05 20:30:30] IP 127.0.0.1 tried to access /dev/dashboard/logs and received status 200  - 2025-01-05 20:30:30,449
127.0.0.1 - - [05/Jan/2025 20:30:30] "GET /dev/dashboard/logs HTTP/1.1" 200 - - 2025-01-05 20:30:30,449
[LOG] [2025-01-05 20:30:30] IP 127.0.0.1 tried to access /api/v1/dev/logs and received status 200  - 2025-01-05 20:30:30,582
127.0.0.1 - - [05/Jan/2025 20:30:30] "GET /api/v1/dev/logs HTTP/1.1" 200 - - 2025-01-05 20:30:30,582
[LOG] [2025-01-05 20:30:31] IP 127.0.0.1 tried to access /dev/dashboard/logs and received status 200  - 2025-01-05 20:30:31,731
127.0.0.1 - - [05/Jan/2025 20:30:31] "GET /dev/dashboard/logs HTTP/1.1" 200 - - 2025-01-05 20:30:31,732
[LOG] [2025-01-05 20:30:31] IP 127.0.0.1 tried to access /api/v1/dev/logs and received status 200  - 2025-01-05 20:30:31,822
127.0.0.1 - - [05/Jan/2025 20:30:31] "GET /api/v1/dev/logs HTTP/1.1" 200 - - 2025-01-05 20:30:31,823
[LOG] [2025-01-05 20:30:32] IP 127.0.0.1 tried to access /dev/dashboard/token_request and received status 200  - 2025-01-05 20:30:32,144
127.0.0.1 - - [05/Jan/2025 20:30:32] "GET /dev/dashboard/token_request HTTP/1.1" 200 - - 2025-01-05 20:30:32,145
[LOG] [2025-01-05 20:30:32] IP 127.0.0.1 tried to access /api/v1/dev/pending_requests and received status 200  - 2025-01-05 20:30:32,310
127.0.0.1 - - [05/Jan/2025 20:30:32] "GET /api/v1/dev/pending_requests HTTP/1.1" 200 - - 2025-01-05 20:30:32,311
[LOG] [2025-01-05 20:30:32] IP 127.0.0.1 tried to access /dev/dashboard/firewall and received status 200  - 2025-01-05 20:30:32,662
127.0.0.1 - - [05/Jan/2025 20:30:32] "GET /dev/dashboard/firewall HTTP/1.1" 200 - - 2025-01-05 20:30:32,663
[LOG] [2025-01-05 20:30:32] IP 127.0.0.1 tried to access /api/v1/dev/blocklist and received status 200  - 2025-01-05 20:30:32,784
127.0.0.1 - - [05/Jan/2025 20:30:32] "GET /api/v1/dev/blocklist HTTP/1.1" 200 - - 2025-01-05 20:30:32,784
[LOG] [2025-01-05 20:30:35] IP 127.0.0.1 tried to access /dev/dashboard/token_request and received status 200  - 2025-01-05 20:30:35,962
127.0.0.1 - - [05/Jan/2025 20:30:35] "GET /dev/dashboard/token_request HTTP/1.1" 200 - - 2025-01-05 20:30:35,962
[LOG] [2025-01-05 20:30:36] IP 127.0.0.1 tried to access /api/v1/dev/pending_requests and received status 200  - 2025-01-05 20:30:36,111
127.0.0.1 - - [05/Jan/2025 20:30:36] "GET /api/v1/dev/pending_requests HTTP/1.1" 200 - - 2025-01-05 20:30:36,111
[LOG] [2025-01-05 20:30:41] IP 127.0.0.1 tried to access /dev/logout and received status 302  - 2025-01-05 20:30:41,435
127.0.0.1 - - [05/Jan/2025 20:30:41] "[32mGET /dev/logout HTTP/1.1[0m" 302 - - 2025-01-05 20:30:41,436
[LOG] [2025-01-05 20:30:41] IP 127.0.0.1 tried to access / and received status 200  - 2025-01-05 20:30:41,457
127.0.0.1 - - [05/Jan/2025 20:30:41] "GET / HTTP/1.1" 200 - - 2025-01-05 20:30:41,458
[LOG] [2025-01-05 20:30:41] IP 127.0.0.1 tried to access /static/icon.png and received status 304  - 2025-01-05 20:30:41,576
[LOG] [2025-01-05 20:30:41] IP 127.0.0.1 tried to access /static/phone-window.jpg and received status 304  - 2025-01-05 20:30:41,576
127.0.0.1 - - [05/Jan/2025 20:30:41] "[36mGET /static/icon.png HTTP/1.1[0m" 304 - - 2025-01-05 20:30:41,577
127.0.0.1 - - [05/Jan/2025 20:30:41] "[36mGET /static/phone-window.jpg HTTP/1.1[0m" 304 - - 2025-01-05 20:30:41,577
[LOG] [2025-01-05 20:31:12] IP 127.0.0.1 tried to access /dev/logout and received status 302  - 2025-01-05 20:31:12,016
127.0.0.1 - - [05/Jan/2025 20:31:12] "[32mGET /dev/logout HTTP/1.1[0m" 302 - - 2025-01-05 20:31:12,016
[LOG] [2025-01-05 20:31:12] IP 127.0.0.1 tried to access / and received status 200  - 2025-01-05 20:31:12,043
127.0.0.1 - - [05/Jan/2025 20:31:12] "GET / HTTP/1.1" 200 - - 2025-01-05 20:31:12,044
[LOG] [2025-01-05 20:31:12] IP 127.0.0.1 tried to access /static/icon.png and received status 304  - 2025-01-05 20:31:12,178
127.0.0.1 - - [05/Jan/2025 20:31:12] "[36mGET /static/icon.png HTTP/1.1[0m" 304 - - 2025-01-05 20:31:12,178
[LOG] [2025-01-05 20:31:12] IP 127.0.0.1 tried to access /static/phone-window.jpg and received status 304  - 2025-01-05 20:31:12,181
127.0.0.1 - - [05/Jan/2025 20:31:12] "[36mGET /static/phone-window.jpg HTTP/1.1[0m" 304 - - 2025-01-05 20:31:12,181
[LOG] [2025-01-05 20:32:00] IP 127.0.0.1 tried to access /dev/login and received status 200  - 2025-01-05 20:32:00,546
127.0.0.1 - - [05/Jan/2025 20:32:00] "GET /dev/login HTTP/1.1" 200 - - 2025-01-05 20:32:00,547
[LOG] [2025-01-05 20:32:04] IP 127.0.0.1 tried to access /dev/login and received status 302  - 2025-01-05 20:32:04,512
127.0.0.1 - - [05/Jan/2025 20:32:04] "[32mPOST /dev/login HTTP/1.1[0m" 302 - - 2025-01-05 20:32:04,513
[LOG] [2025-01-05 20:32:04] IP 127.0.0.1 tried to access /dev/dashboard/home and received status 200  - 2025-01-05 20:32:04,532
127.0.0.1 - - [05/Jan/2025 20:32:04] "GET /dev/dashboard/home HTTP/1.1" 200 - - 2025-01-05 20:32:04,532
[LOG] [2025-01-05 20:32:04] IP 127.0.0.1 tried to access /api/v1/check_health and received status 200  - 2025-01-05 20:32:04,693
127.0.0.1 - - [05/Jan/2025 20:32:04] "GET /api/v1/check_health HTTP/1.1" 200 - - 2025-01-05 20:32:04,694
[LOG] [2025-01-05 20:32:04] IP 127.0.0.1 tried to access /api/v1/dev/alerts and received status 200  - 2025-01-05 20:32:04,699
127.0.0.1 - - [05/Jan/2025 20:32:04] "GET /api/v1/dev/alerts HTTP/1.1" 200 - - 2025-01-05 20:32:04,700
[LOG] [2025-01-05 20:32:10] IP 127.0.0.1 tried to access / and received status 200  - 2025-01-05 20:32:10,008
127.0.0.1 - - [05/Jan/2025 20:32:10] "GET / HTTP/1.1" 200 - - 2025-01-05 20:32:10,008
[LOG] [2025-01-05 20:32:10] IP 127.0.0.1 tried to access /static/icon.png and received status 304  - 2025-01-05 20:32:10,127
127.0.0.1 - - [05/Jan/2025 20:32:10] "[36mGET /static/icon.png HTTP/1.1[0m" 304 - - 2025-01-05 20:32:10,128
[LOG] [2025-01-05 20:32:10] IP 127.0.0.1 tried to access /static/phone-window.jpg and received status 200  - 2025-01-05 20:32:10,146
127.0.0.1 - - [05/Jan/2025 20:32:10] "GET /static/phone-window.jpg HTTP/1.1" 200 - - 2025-01-05 20:32:10,146
127.0.0.1 - - [05/Jan/2025 20:32:12] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:32:12,250
127.0.0.1 - - [05/Jan/2025 20:32:12] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 - - 2025-01-05 20:32:12,341
127.0.0.1 - - [05/Jan/2025 20:32:12] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 - - 2025-01-05 20:32:12,344
127.0.0.1 - - [05/Jan/2025 20:32:12] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=console.png&s=xD4eEIpifa87GXGjrEcf HTTP/1.1[0m" 304 - - 2025-01-05 20:32:12,426
127.0.0.1 - - [05/Jan/2025 20:32:15] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:32:15,824
127.0.0.1 - - [05/Jan/2025 20:32:16] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 - - 2025-01-05 20:32:16,043
127.0.0.1 - - [05/Jan/2025 20:32:16] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 - - 2025-01-05 20:32:16,045
127.0.0.1 - - [05/Jan/2025 20:32:16] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=console.png&s=xD4eEIpifa87GXGjrEcf HTTP/1.1[0m" 304 - - 2025-01-05 20:32:16,305
127.0.0.1 - - [05/Jan/2025 20:33:54] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:33:54,357
127.0.0.1 - - [05/Jan/2025 20:33:54] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 - - 2025-01-05 20:33:54,548
127.0.0.1 - - [05/Jan/2025 20:33:54] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 - - 2025-01-05 20:33:54,552
127.0.0.1 - - [05/Jan/2025 20:33:54] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=console.png&s=xD4eEIpifa87GXGjrEcf HTTP/1.1[0m" 304 - - 2025-01-05 20:33:54,828
127.0.0.1 - - [05/Jan/2025 20:33:55] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:33:55,478
127.0.0.1 - - [05/Jan/2025 20:33:55] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 - - 2025-01-05 20:33:55,609
127.0.0.1 - - [05/Jan/2025 20:33:55] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 - - 2025-01-05 20:33:55,610
127.0.0.1 - - [05/Jan/2025 20:33:55] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=console.png&s=xD4eEIpifa87GXGjrEcf HTTP/1.1[0m" 304 - - 2025-01-05 20:33:55,865
 * Detected change in '/home/mint/Desktop/Vault-7/backend-api/app.py', reloading - 2025-01-05 20:36:53,317
 * Restarting with stat - 2025-01-05 20:36:53,537
 * Debugger is active! - 2025-01-05 20:36:54,364
 * Debugger PIN: 732-635-082 - 2025-01-05 20:36:54,368
127.0.0.1 - - [05/Jan/2025 20:36:54] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:36:54,468
127.0.0.1 - - [05/Jan/2025 20:36:54] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 - - 2025-01-05 20:36:54,686
127.0.0.1 - - [05/Jan/2025 20:36:54] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 - - 2025-01-05 20:36:54,687
127.0.0.1 - - [05/Jan/2025 20:36:54] "GET /user/portal?__debugger__=yes&cmd=resource&f=console.png&s=sHxUXuv9PT4oViwYimuM HTTP/1.1" 200 - - 2025-01-05 20:36:54,785
127.0.0.1 - - [05/Jan/2025 20:37:00] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:37:00,373
127.0.0.1 - - [05/Jan/2025 20:37:00] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 - - 2025-01-05 20:37:00,503
127.0.0.1 - - [05/Jan/2025 20:37:00] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 - - 2025-01-05 20:37:00,504
127.0.0.1 - - [05/Jan/2025 20:37:00] "[36mGET /user/portal?__debugger__=yes&cmd=resource&f=console.png&s=sHxUXuv9PT4oViwYimuM HTTP/1.1[0m" 304 - - 2025-01-05 20:37:00,589
 * Detected change in '/home/mint/Desktop/Vault-7/backend-api/app.py', reloading - 2025-01-05 20:37:03,570
 * Restarting with stat - 2025-01-05 20:37:03,779
 * Debugger is active! - 2025-01-05 20:37:04,563
 * Debugger PIN: 732-635-082 - 2025-01-05 20:37:04,569
 * Detected change in '/home/mint/Desktop/Vault-7/backend-api/app.py', reloading - 2025-01-05 20:37:27,154
 * Restarting with stat - 2025-01-05 20:37:27,440
Exception on /user/portal [GET] - 2025-01-05 20:37:28,234
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:37:28] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:37:28,241
127.0.0.1 - - [05/Jan/2025 20:37:28] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:37:28,242
Exception on /user/portal [GET] - 2025-01-05 20:37:32,581
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:37:32] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:37:32,584
127.0.0.1 - - [05/Jan/2025 20:37:32] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:37:32,584
Exception on /user/portal [GET] - 2025-01-05 20:40:40,637
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:40:40] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:40:40,639
127.0.0.1 - - [05/Jan/2025 20:40:40] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:40:40,639
Exception on /user/portal [GET] - 2025-01-05 20:40:41,590
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:40:41] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:40:41,591
127.0.0.1 - - [05/Jan/2025 20:40:41] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:40:41,592
Exception on /user/portal [GET] - 2025-01-05 20:40:41,785
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:40:41] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:40:41,787
127.0.0.1 - - [05/Jan/2025 20:40:41] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:40:41,787
Exception on /user/portal [GET] - 2025-01-05 20:40:48,311
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:40:48] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:40:48,312
127.0.0.1 - - [05/Jan/2025 20:40:48] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:40:48,313
[LOG] [2025-01-05 20:40:51] IP 127.0.0.1 tried to access / and received status 200  - 2025-01-05 20:40:51,106
127.0.0.1 - - [05/Jan/2025 20:40:51] "GET / HTTP/1.1" 200 - - 2025-01-05 20:40:51,107
[LOG] [2025-01-05 20:40:51] IP 127.0.0.1 tried to access /static/icon.png and received status 304  - 2025-01-05 20:40:51,332
127.0.0.1 - - [05/Jan/2025 20:40:51] "[36mGET /static/icon.png HTTP/1.1[0m" 304 - - 2025-01-05 20:40:51,333
[LOG] [2025-01-05 20:40:51] IP 127.0.0.1 tried to access /static/phone-window.jpg and received status 304  - 2025-01-05 20:40:51,338
127.0.0.1 - - [05/Jan/2025 20:40:51] "[36mGET /static/phone-window.jpg HTTP/1.1[0m" 304 - - 2025-01-05 20:40:51,339
Exception on /user/portal [GET] - 2025-01-05 20:40:53,243
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:40:53] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:40:53,245
127.0.0.1 - - [05/Jan/2025 20:40:53] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:40:53,246
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.31.170:5000 - 2025-01-05 20:41:01,674
[33mPress CTRL+C to quit[0m - 2025-01-05 20:41:01,674
Exception on /user/portal [GET] - 2025-01-05 20:41:03,006
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:41:03] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:41:03,015
127.0.0.1 - - [05/Jan/2025 20:41:03] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:41:03,017
[LOG] [2025-01-05 20:41:03] IP 127.0.0.1 tried to access /static/500-logo.png and received status 200  - 2025-01-05 20:41:03,105
127.0.0.1 - - [05/Jan/2025 20:41:03] "GET /static/500-logo.png HTTP/1.1" 200 - - 2025-01-05 20:41:03,105
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.31.170:5000 - 2025-01-05 20:41:37,198
[33mPress CTRL+C to quit[0m - 2025-01-05 20:41:37,199
Exception on /user/portal [GET] - 2025-01-05 20:41:37,502
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:41:37] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:41:37,511
127.0.0.1 - - [05/Jan/2025 20:41:37] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:41:37,512
[LOG] [2025-01-05 20:41:37] IP 127.0.0.1 tried to access /static/500-logo.png and received status 304  - 2025-01-05 20:41:37,629
127.0.0.1 - - [05/Jan/2025 20:41:37] "[36mGET /static/500-logo.png HTTP/1.1[0m" 304 - - 2025-01-05 20:41:37,629
Exception on /user/portal [GET] - 2025-01-05 20:42:13,315
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:42:13] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:42:13,316
127.0.0.1 - - [05/Jan/2025 20:42:13] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:42:13,317
[LOG] [2025-01-05 20:42:13] IP 127.0.0.1 tried to access /static/500-logo.png and received status 304  - 2025-01-05 20:42:13,427
127.0.0.1 - - [05/Jan/2025 20:42:13] "[36mGET /static/500-logo.png HTTP/1.1[0m" 304 - - 2025-01-05 20:42:13,428
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.31.170:5000 - 2025-01-05 20:42:17,155
[33mPress CTRL+C to quit[0m - 2025-01-05 20:42:17,155
Exception on /user/portal [GET] - 2025-01-05 20:42:17,284
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:42:17] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:42:17,293
127.0.0.1 - - [05/Jan/2025 20:42:17] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:42:17,294
[LOG] [2025-01-05 20:42:17] IP 127.0.0.1 tried to access /static/500-logo.png and received status 304  - 2025-01-05 20:42:17,420
127.0.0.1 - - [05/Jan/2025 20:42:17] "[36mGET /static/500-logo.png HTTP/1.1[0m" 304 - - 2025-01-05 20:42:17,420
Exception on /user/portal [GET] - 2025-01-05 20:44:47,016
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:44:47] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:44:47,018
127.0.0.1 - - [05/Jan/2025 20:44:47] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:44:47,019
[LOG] [2025-01-05 20:44:47] IP 127.0.0.1 tried to access /static/500-logo.png and received status 304  - 2025-01-05 20:44:47,123
127.0.0.1 - - [05/Jan/2025 20:44:47] "[36mGET /static/500-logo.png HTTP/1.1[0m" 304 - - 2025-01-05 20:44:47,125
Exception on /user/portal [GET] - 2025-01-05 20:44:48,094
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:44:48] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:44:48,101
127.0.0.1 - - [05/Jan/2025 20:44:48] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:44:48,101
[LOG] [2025-01-05 20:44:48] IP 127.0.0.1 tried to access /static/500-logo.png and received status 304  - 2025-01-05 20:44:48,296
127.0.0.1 - - [05/Jan/2025 20:44:48] "[36mGET /static/500-logo.png HTTP/1.1[0m" 304 - - 2025-01-05 20:44:48,296
[LOG] [2025-01-05 20:47:49] IP 127.0.0.1 tried to access /favicon.ico and received status 404  - 2025-01-05 20:47:49,056
127.0.0.1 - - [05/Jan/2025 20:47:49] "[33mGET /favicon.ico HTTP/1.1[0m" 404 - - 2025-01-05 20:47:49,057
[LOG] [2025-01-05 20:47:49] IP 127.0.0.1 tried to access / and received status 200  - 2025-01-05 20:47:49,879
127.0.0.1 - - [05/Jan/2025 20:47:49] "GET / HTTP/1.1" 200 - - 2025-01-05 20:47:49,880
[LOG] [2025-01-05 20:47:50] IP 127.0.0.1 tried to access /static/icon.png and received status 304  - 2025-01-05 20:47:50,024
[LOG] [2025-01-05 20:47:50] IP 127.0.0.1 tried to access /static/phone-window.jpg and received status 304  - 2025-01-05 20:47:50,026
127.0.0.1 - - [05/Jan/2025 20:47:50] "[36mGET /static/icon.png HTTP/1.1[0m" 304 - - 2025-01-05 20:47:50,026
127.0.0.1 - - [05/Jan/2025 20:47:50] "[36mGET /static/phone-window.jpg HTTP/1.1[0m" 304 - - 2025-01-05 20:47:50,027
[LOG] [2025-01-05 20:47:50] IP 127.0.0.1 tried to access / and received status 200  - 2025-01-05 20:47:50,699
127.0.0.1 - - [05/Jan/2025 20:47:50] "GET / HTTP/1.1" 200 - - 2025-01-05 20:47:50,699
[LOG] [2025-01-05 20:47:50] IP 127.0.0.1 tried to access /static/phone-window.jpg and received status 304  - 2025-01-05 20:47:50,772
127.0.0.1 - - [05/Jan/2025 20:47:50] "[36mGET /static/phone-window.jpg HTTP/1.1[0m" 304 - - 2025-01-05 20:47:50,773
[LOG] [2025-01-05 20:47:50] IP 127.0.0.1 tried to access /static/icon.png and received status 304  - 2025-01-05 20:47:50,774
127.0.0.1 - - [05/Jan/2025 20:47:50] "[36mGET /static/icon.png HTTP/1.1[0m" 304 - - 2025-01-05 20:47:50,774
[LOG] [2025-01-05 20:47:50] IP 127.0.0.1 tried to access / and received status 200  - 2025-01-05 20:47:50,869
127.0.0.1 - - [05/Jan/2025 20:47:50] "GET / HTTP/1.1" 200 - - 2025-01-05 20:47:50,869
[LOG] [2025-01-05 20:47:50] IP 127.0.0.1 tried to access /static/phone-window.jpg and received status 304  - 2025-01-05 20:47:50,935
127.0.0.1 - - [05/Jan/2025 20:47:50] "[36mGET /static/phone-window.jpg HTTP/1.1[0m" 304 - - 2025-01-05 20:47:50,936
[LOG] [2025-01-05 20:47:50] IP 127.0.0.1 tried to access /static/icon.png and received status 304  - 2025-01-05 20:47:50,937
127.0.0.1 - - [05/Jan/2025 20:47:50] "[36mGET /static/icon.png HTTP/1.1[0m" 304 - - 2025-01-05 20:47:50,939
[LOG] [2025-01-05 20:47:52] IP 127.0.0.1 tried to access /services and received status 200  - 2025-01-05 20:47:52,676
127.0.0.1 - - [05/Jan/2025 20:47:52] "GET /services HTTP/1.1" 200 - - 2025-01-05 20:47:52,677
[LOG] [2025-01-05 20:47:52] IP 127.0.0.1 tried to access /static/icon.png and received status 304  - 2025-01-05 20:47:52,804
[LOG] [2025-01-05 20:47:52] IP 127.0.0.1 tried to access /static/screen-window.png and received status 304  - 2025-01-05 20:47:52,805
127.0.0.1 - - [05/Jan/2025 20:47:52] "[36mGET /static/icon.png HTTP/1.1[0m" 304 - - 2025-01-05 20:47:52,805
[LOG] [2025-01-05 20:47:52] IP 127.0.0.1 tried to access /static/phone-window.jpg and received status 304  - 2025-01-05 20:47:52,806
127.0.0.1 - - [05/Jan/2025 20:47:52] "[36mGET /static/phone-window.jpg HTTP/1.1[0m" 304 - - 2025-01-05 20:47:52,807
127.0.0.1 - - [05/Jan/2025 20:47:52] "[36mGET /static/screen-window.png HTTP/1.1[0m" 304 - - 2025-01-05 20:47:52,806
Exception on /user/portal [GET] - 2025-01-05 20:47:54,009
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 830, in portal
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:47:54] IP 127.0.0.1 tried to access /user/portal and received status 500  - 2025-01-05 20:47:54,011
127.0.0.1 - - [05/Jan/2025 20:47:54] "[35m[1mGET /user/portal HTTP/1.1[0m" 500 - - 2025-01-05 20:47:54,011
[LOG] [2025-01-05 20:47:54] IP 127.0.0.1 tried to access /static/500-logo.png and received status 304  - 2025-01-05 20:47:54,138
127.0.0.1 - - [05/Jan/2025 20:47:54] "[36mGET /static/500-logo.png HTTP/1.1[0m" 304 - - 2025-01-05 20:47:54,138
Exception on /user/myaccount [GET] - 2025-01-05 20:47:59,430
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mint/Desktop/Vault-7/backend-api/app.py", line 809, in user_myaccount
    email = session['email']
            ~~~~~~~^^^^^^^^^
  File "/home/mint/.local/lib/python3.12/site-packages/flask/sessions.py", line 86, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'email'
[LOG] [2025-01-05 20:47:59] IP 127.0.0.1 tried to access /user/myaccount and received status 500  - 2025-01-05 20:47:59,432
127.0.0.1 - - [05/Jan/2025 20:47:59] "[35m[1mGET /user/myaccount HTTP/1.1[0m" 500 - - 2025-01-05 20:47:59,433
[LOG] [2025-01-05 20:47:59] IP 127.0.0.1 tried to access /static/500-logo.png and received status 304  - 2025-01-05 20:47:59,540
127.0.0.1 - - [05/Jan/2025 20:47:59] "[36mGET /static/500-logo.png HTTP/1.1[0m" 304 - - 2025-01-05 20:47:59,540
[LOG] [2025-01-05 20:48:17] IP 127.0.0.1 tried to access /user/myaccount and received status 302  - 2025-01-05 20:48:17,029
127.0.0.1 - - [05/Jan/2025 20:48:17] "[32mGET /user/myaccount HTTP/1.1[0m" 302 - - 2025-01-05 20:48:17,030
[LOG] [2025-01-05 20:48:17] IP 127.0.0.1 tried to access /user/login and received status 200  - 2025-01-05 20:48:17,057
127.0.0.1 - - [05/Jan/2025 20:48:17] "GET /user/login HTTP/1.1" 200 - - 2025-01-05 20:48:17,058
[LOG] [2025-01-05 20:48:18] IP 127.0.0.1 tried to access / and received status 200  - 2025-01-05 20:48:18,388
127.0.0.1 - - [05/Jan/2025 20:48:18] "GET / HTTP/1.1" 200 - - 2025-01-05 20:48:18,388
[LOG] [2025-01-05 20:48:18] IP 127.0.0.1 tried to access /static/icon.png and received status 304  - 2025-01-05 20:48:18,521
127.0.0.1 - - [05/Jan/2025 20:48:18] "[36mGET /static/icon.png HTTP/1.1[0m" 304 - - 2025-01-05 20:48:18,522
[LOG] [2025-01-05 20:48:18] IP 127.0.0.1 tried to access /static/phone-window.jpg and received status 304  - 2025-01-05 20:48:18,524
127.0.0.1 - - [05/Jan/2025 20:48:18] "[36mGET /static/phone-window.jpg HTTP/1.1[0m" 304 - - 2025-01-05 20:48:18,524
[LOG] [2025-01-05 20:48:29] IP 127.0.0.1 tried to access /docs and received status 404  - 2025-01-05 20:48:29,072
127.0.0.1 - - [05/Jan/2025 20:48:29] "[33mGET /docs HTTP/1.1[0m" 404 - - 2025-01-05 20:48:29,072
[LOG] [2025-01-05 20:48:32] IP 127.0.0.1 tried to access /dev/docs and received status 404  - 2025-01-05 20:48:32,826
127.0.0.1 - - [05/Jan/2025 20:48:32] "[33mGET /dev/docs HTTP/1.1[0m" 404 - - 2025-01-05 20:48:32,826
[LOG] [2025-01-05 20:48:39] IP 127.0.0.1 tried to access /dev/api/v1/docs and received status 404  - 2025-01-05 20:48:39,565
127.0.0.1 - - [05/Jan/2025 20:48:39] "[33mGET /dev/api/v1/docs HTTP/1.1[0m" 404 - - 2025-01-05 20:48:39,566
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.31.170:5000 - 2025-01-05 20:49:09,954
[33mPress CTRL+C to quit[0m - 2025-01-05 20:49:09,954
[LOG] [2025-01-05 20:49:11] IP 127.0.0.1 tried to access /dev/api/v1/docs and received status 404  - 2025-01-05 20:49:11,350
127.0.0.1 - - [05/Jan/2025 20:49:11] "[33mGET /dev/api/v1/docs HTTP/1.1[0m" 404 - - 2025-01-05 20:49:11,351
[LOG] [2025-01-05 20:49:15] IP 127.0.0.1 tried to access /dev/docs and received status 403  - 2025-01-05 20:49:15,253
127.0.0.1 - - [05/Jan/2025 20:49:15] "[31m[1mGET /dev/docs HTTP/1.1[0m" 403 - - 2025-01-05 20:49:15,254
